# -*- coding: utf-8 -*-
"""genai.gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrcs0mpCLCu9I_1FFF9tLE8OEHSbz9P6
"""

import json
data=json.load(open("/content/states_india.geojson"))
print(data)

json.load(open("/content/states_india.geojson"))

for feature in data['features']:
 state_name=feature['properties']['st_nm']
 print(state_name)

type (data)
dict

type(data)['features']

type (data).keys

data['features'][0].keys()

data['features'][0]['properties']

data['features'][0]['properties']['st_nm']

data['features'][1]['properties']['st_nm']

data['features'][25]['properties']['st_nm']

engine_mode="gpt-3.5-turbo"

!pip install openai==0.28

import openai
openai.api_key="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"

openai.models.list()

models=openai.models.list()

type(models.data)

openai.Completion.create(engine="gpt-3.5-turbo",prompt="tell me about India in 100 words",max_tokens=1024,n=1,temperature=0.5)

!pip install openai==0.28

!pip install langchain-openai

!pip install-q-U goole-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyAfKFleC_CUWv5Uo6ovN-8_Z7EVy4H53nQ")

for i in genai.list_models():
  print(i.name)

model=genai.GenerativeModel("gemini-pro")

res=model.generate_content("List out the district in Tamilnadu")

print(res.text)

res=model.generate_content("where is attur in india")

print(res.text)

res=model.generate_content("where is salem district in tamil nadu")

print(res.text)

internet=model.generate_content("what is arpanet")

print(internet.text)

vision_model=genai.GenerativeModel("gemini-1.5-flash")

from PIL import Image
Img=Image.open("/content/download.np.jpg")

Img

vision_model.generate_content(["what the image telling",Img])

